- name: Install Apache
  apt:
    name: "{{ apache_packages }}"
    state: present
    update_cache: yes
  notify:
    - Restart Apache

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: yes
